### ISSUE TITLE
Portuguese podcast transcribed to English

### ISSUE THREAD

**Issue by dnng** [diegoquinteiro/podcast-summarizer#2]
Steps to reproduce:

1. Get a youtube video in portuguese: https://www.youtube.com/watch?v=JJ7NQRcLvd8
2. Call podcast-summarizer as: `podcast-summarizer https://www.youtube.com/watch?v=JJ7NQRcLvd8`

Expected result:
1. yt-audio.txt generated in portuguese

Observed result:
1. yt-audio.txt generated in english

**Comment by diegoquinteiro** [comment]
Fixed by #3
